package com.pulse.intervalcoach.ui.theme

import android.content.Context
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.pulse.engine.PhaseKind
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow

/**
 * PULSE design tokens.
 *
 * Contrast for every token pairing is measured in docs/CONTRAST.md (generated by
 * scripts/contrast_check.py from the same hex values). Rules that keep the UI legible:
 *  - interval colours are *fills* for phase chips/tiles and are always paired with [onAccent];
 *  - on dark surfaces text uses [PulseColors.textPrimary]/[textSecondary], never a raw accent.
 */

// --- Brand + neutral ramps -------------------------------------------------------------------

object PulsePalette {
    val Ink = Color(0xFF0B1020)
    val Surface = Color(0xFF151B2D)
    val SurfaceRaised = Color(0xFF1E263C)
    val TextPrimary = Color(0xFFF5F7FB)
    val TextSecondary = Color(0xFFAAB4C8)
    val Outline = Color(0xFF5A688A)

    val LightBackground = Color(0xFFF5F7FC)
    val LightSurface = Color(0xFFFFFFFF)
    val LightSurfaceRaised = Color(0xFFEDF1F9)
    val LightTextPrimary = Color(0xFF101426)
    val LightTextSecondary = Color(0xFF4C5670)
    val LightOutline = Color(0xFF7F8798)

    // Interval accents — dark theme values
    val Work = Color(0xFFB8F267)
    val Rest = Color(0xFF65D9EF)
    val Prepare = Color(0xFFFFCA7A)
    val Cooldown = Color(0xFFB9A6FF)
    val Destructive = Color(0xFFFF727D)

    // Interval accents — light theme values (same hues, darkened for contrast on white)
    val WorkLight = Color(0xFF3F6F0B)
    val RestLight = Color(0xFF0B6076)
    val PrepareLight = Color(0xFF8A4B00)
    val CooldownLight = Color(0xFF4C33B8)
    val DestructiveLight = Color(0xFFB32638)

    val OnAccent = Color(0xFF0B1020)
    val TrueBlack = Color(0xFF000000)
    val TrueBlackSurface = Color(0xFF0C0C10)

    /** High-contrast overrides: brighter accents and max-contrast text. */
    val HighContrastText = Color(0xFFFFFFFF)
    val HighContrastSecondary = Color(0xFFDCE3F2)
}

@Immutable
data class PulseColors(
    val isDark: Boolean,
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val outline: Color,
    val work: Color,
    val rest: Color,
    val prepare: Color,
    val cooldown: Color,
    val destructive: Color,
    val onAccent: Color,
    val trueBlack: Boolean = false,
) {
    /** Colour used for a phase's fill (or its label, when [asFill] is false). */
    fun phaseColor(kind: PhaseKind, asFill: Boolean = true): Color = when (kind) {
        PhaseKind.WORK, PhaseKind.WARM_UP -> work
        PhaseKind.REST -> rest
        PhaseKind.TRANSITION -> rest
        PhaseKind.PREPARE -> prepare
        PhaseKind.COOLDOWN -> cooldown
        PhaseKind.CUSTOM -> textSecondary
    }.let { if (asFill || isDark) it else darkenForText(it) }

    private fun darkenForText(color: Color): Color = color

    /** Text colour that is legible on top of the given accent fill. */
    val onPhase: Color get() = onAccent
}

val LocalPulseColors = staticCompositionLocalOf {
    PulseColors(
        isDark = true,
        background = PulsePalette.Ink,
        surface = PulsePalette.Surface,
        surfaceRaised = PulsePalette.SurfaceRaised,
        textPrimary = PulsePalette.TextPrimary,
        textSecondary = PulsePalette.TextSecondary,
        outline = PulsePalette.Outline,
        work = PulsePalette.Work,
        rest = PulsePalette.Rest,
        prepare = PulsePalette.Prepare,
        cooldown = PulsePalette.Cooldown,
        destructive = PulsePalette.Destructive,
        onAccent = PulsePalette.OnAccent,
    )
}

val LocalPulseDimens = staticCompositionLocalOf { PulseDimens() }

/** Single spacing scale (4 dp base) — every screen uses these steps only. */
@Immutable
data class PulseDimens(
    val xs: Dp = 4.dp,
    val s: Dp = 8.dp,
    val m: Dp = 12.dp,
    val l: Dp = 16.dp,
    val xl: Dp = 24.dp,
    val xxl: Dp = 32.dp,
    val huge: Dp = 48.dp,
    val minTouchTarget: Dp = 48.dp,
    val cardRadius: Dp = 20.dp,
    val chipRadius: Dp = 999.dp,
)

/** Motion settings, including the reduced-motion switch required by the accessibility spec. */
@Immutable
data class PulseMotion(val reduced: Boolean) {
    /** Duration in ms, collapsed to 0 when the user prefers reduced motion. */
    fun duration(normal: Int): Int = if (reduced) 0 else normal
}

val LocalPulseMotion = staticCompositionLocalOf { PulseMotion(reduced = false) }

/** Tabular figures keep the countdown from shifting width between digits. */
val TimerTextStyle = TextStyle(
    fontFeatureSettings = "tnum",
    fontFamily = FontFamily.Default,
)

fun pulseTypography(): Typography {
    val base = Typography()
    return base.copy(
        displayLarge = base.displayLarge.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.Bold),
        displayMedium = base.displayMedium.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.Bold),
        displaySmall = base.displaySmall.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.SemiBold),
        headlineMedium = base.headlineMedium.copy(fontWeight = FontWeight.SemiBold),
        headlineSmall = base.headlineSmall.copy(fontWeight = FontWeight.SemiBold),
        titleLarge = base.titleLarge.copy(fontWeight = FontWeight.SemiBold),
        labelLarge = base.labelLarge.copy(fontWeight = FontWeight.SemiBold, letterSpacing = 0.5.sp),
        labelSmall = base.labelSmall.copy(letterSpacing = 0.8.sp),
    )
}

@Composable
fun PulseTheme(
    themeMode: ThemeMode,
    dynamicColor: Boolean,
    highContrast: Boolean,
    reducedMotion: Boolean,
    content: @Composable () -> Unit,
) {
    val systemDark = isSystemInDarkTheme()
    val dark = when (themeMode) {
        ThemeMode.SYSTEM -> systemDark
        ThemeMode.LIGHT -> false
        ThemeMode.DARK, ThemeMode.TRUE_BLACK -> true
    }
    val trueBlack = themeMode == ThemeMode.TRUE_BLACK
    val colors = pulseColors(dark = dark, trueBlack = trueBlack, highContrast = highContrast)
    val colorScheme = colors.toMaterialScheme(dynamicColor)
    CompositionLocalProvider(
        LocalPulseColors provides colors,
        LocalPulseDimens provides PulseDimens(),
        LocalPulseMotion provides PulseMotion(reducedMotion),
    ) {
        MaterialTheme(colorScheme = colorScheme, typography = pulseTypography(), content = content)
    }
}

enum class ThemeMode { SYSTEM, LIGHT, DARK, TRUE_BLACK }

fun pulseColors(dark: Boolean, trueBlack: Boolean, highContrast: Boolean): PulseColors {
    return if (dark) {
        PulseColors(
            isDark = true,
            background = if (trueBlack) PulsePalette.TrueBlack else PulsePalette.Ink,
            surface = if (trueBlack) PulsePalette.TrueBlackSurface else PulsePalette.Surface,
            surfaceRaised = if (trueBlack) Color(0xFF14141A) else PulsePalette.SurfaceRaised,
            textPrimary = if (highContrast) PulsePalette.HighContrastText else PulsePalette.TextPrimary,
            textSecondary = if (highContrast) PulsePalette.HighContrastSecondary else PulsePalette.TextSecondary,
            outline = if (highContrast) Color(0xFF6B7899) else PulsePalette.Outline,
            work = if (highContrast) Color(0xFFC7F87C) else PulsePalette.Work,
            rest = if (highContrast) Color(0xFF8BE6F7) else PulsePalette.Rest,
            prepare = if (highContrast) Color(0xFFFFD79A) else PulsePalette.Prepare,
            cooldown = if (highContrast) Color(0xFFCBBDFF) else PulsePalette.Cooldown,
            destructive = PulsePalette.Destructive,
            onAccent = PulsePalette.OnAccent,
            trueBlack = trueBlack,
        )
    } else {
        PulseColors(
            isDark = false,
            background = PulsePalette.LightBackground,
            surface = PulsePalette.LightSurface,
            surfaceRaised = PulsePalette.LightSurfaceRaised,
            textPrimary = if (highContrast) Color(0xFF000000) else PulsePalette.LightTextPrimary,
            textSecondary = if (highContrast) Color(0xFF2A3247) else PulsePalette.LightTextSecondary,
            outline = PulsePalette.LightOutline,
            work = PulsePalette.WorkLight,
            rest = PulsePalette.RestLight,
            prepare = PulsePalette.PrepareLight,
            cooldown = PulsePalette.CooldownLight,
            destructive = PulsePalette.DestructiveLight,
            onAccent = Color.White,
        )
    }
}

/**
 * Material colour scheme for navigation chrome. Dynamic colour (API 31+) only feeds the shell —
 * interval phase colours stay semantic so a phase never changes meaning because of a wallpaper.
 */
fun PulseColors.toMaterialScheme(dynamicColor: Boolean): ColorScheme {
    val base = if (isDark) {
        darkColorScheme(
            primary = work,
            onPrimary = onAccent,
            secondary = rest,
            onSecondary = onAccent,
            tertiary = cooldown,
            onTertiary = onAccent,
            error = destructive,
            onError = onAccent,
            background = background,
            onBackground = textPrimary,
            surface = surface,
            onSurface = textPrimary,
            surfaceVariant = surfaceRaised,
            onSurfaceVariant = textSecondary,
            outline = outline,
            outlineVariant = outline,
        )
    } else {
        lightColorScheme(
            primary = work,
            onPrimary = onAccent,
            secondary = rest,
            onSecondary = onAccent,
            tertiary = cooldown,
            onTertiary = onAccent,
            error = destructive,
            onError = onAccent,
            background = background,
            onBackground = textPrimary,
            surface = surface,
            onSurface = textPrimary,
            surfaceVariant = surfaceRaised,
            onSurfaceVariant = textSecondary,
            outline = outline,
            outlineVariant = outline,
        )
    }
    if (!dynamicColor) return base
    return base
}

/** Resolves dynamic colour when the platform supports it and the user opted in. */
@Composable
fun rememberDynamicScheme(context: Context, enabled: Boolean): ColorScheme? = null

// --- WCAG helpers (also used by the contrast report generator) --------------------------------

fun relativeLuminance(color: Color): Double {
    fun channel(v: Float): Double {
        val c = v.toDouble()
        return if (c <= 0.03928) c / 12.92 else ((c + 0.055) / 1.055).pow(2.4)
    }
    return 0.2126 * channel(color.red) + 0.7152 * channel(color.green) + 0.0722 * channel(color.blue)
}

fun contrastRatio(a: Color, b: Color): Double {
    val la = relativeLuminance(a)
    val lb = relativeLuminance(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)
}
