package com.pulse.intervalcoach.ui.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.pulse.engine.PhaseKind
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow

/**
 * PULSE design tokens.
 *
 * Contrast for every token pairing is measured in docs/CONTRAST.md (generated by
 * scripts/contrast_check.py from the same hex values). Rules that keep the UI legible:
 *  - interval colours are *fills* for phase chips/tiles and are always paired with [onAccent];
 *  - on dark surfaces text uses [PulseColors.textPrimary]/[textSecondary], never a raw accent;
 *  - Material components (dialogs, menus, the bottom bar, chips, switches) read the tonal ramp in
 *    [PulseColors.surfaceContainer]…[surfaceContainerHighest], so no Material3 default ever paints
 *    the stock purple-grey baseline on top of the navy palette.
 */

// --- Brand + neutral ramps -------------------------------------------------------------------

object PulsePalette {
    val Ink = Color(0xFF0B1020)
    val Surface = Color(0xFF151B2D)
    val SurfaceRaised = Color(0xFF1E263C)
    val TextPrimary = Color(0xFFF5F7FB)
    val TextSecondary = Color(0xFFAAB4C8)
    val Outline = Color(0xFF5A688A)

    val LightBackground = Color(0xFFF5F7FC)
    val LightSurface = Color(0xFFFFFFFF)
    val LightSurfaceRaised = Color(0xFFEDF1F9)
    val LightTextPrimary = Color(0xFF101426)
    val LightTextSecondary = Color(0xFF4C5670)
    val LightOutline = Color(0xFF7F8798)

    // Interval accents — dark theme values
    val Work = Color(0xFFB8F267)
    val Rest = Color(0xFF65D9EF)
    val Prepare = Color(0xFFFFCA7A)
    val Cooldown = Color(0xFFB9A6FF)
    val Destructive = Color(0xFFFF727D)

    // Interval accents — light theme values (same hues, darkened for contrast on white)
    val WorkLight = Color(0xFF3F6F0B)
    val RestLight = Color(0xFF0B6076)
    val PrepareLight = Color(0xFF8A4B00)
    val CooldownLight = Color(0xFF4C33B8)
    val DestructiveLight = Color(0xFFB32638)

    val OnAccent = Color(0xFF0B1020)
    val TrueBlack = Color(0xFF000000)
    val TrueBlackSurface = Color(0xFF0C0C10)

    /** High-contrast overrides: brighter accents and max-contrast text. */
    val HighContrastText = Color(0xFFFFFFFF)
    val HighContrastSecondary = Color(0xFFDCE3F2)

    // --- Material tonal ramp, dark ---------------------------------------------------------
    // Material3 components pick their container colour from here. Without these the bottom bar,
    // dialogs, menus and switches render in the framework's default purple-grey, which clashes
    // with the navy surfaces around them.
    val DarkContainerLowest = Color(0xFF070B17)
    val DarkContainerLow = Color(0xFF101627)
    val DarkContainerHigh = Color(0xFF1E263C)
    val DarkContainerHighest = Color(0xFF27314A)
    val DarkSurfaceDim = Color(0xFF0B1020)
    val DarkSurfaceBright = Color(0xFF2A3450)
    val DarkOutlineVariant = Color(0xFF2B3552)

    // --- Material tonal ramp, light --------------------------------------------------------
    val LightContainerLowest = Color(0xFFFFFFFF)
    val LightContainerLow = Color(0xFFF7F9FE)
    val LightContainerHigh = Color(0xFFEDF1F9)
    val LightContainerHighest = Color(0xFFE3E9F4)
    val LightSurfaceDim = Color(0xFFDCE2EE)
    val LightSurfaceBright = Color(0xFFFFFFFF)
    val LightOutlineVariant = Color(0xFFD5DBE8)

    // --- Role containers (badges, filled tonal buttons, snackbars) -------------------------
    val DarkPrimaryContainer = Color(0xFF2A3A12)
    val DarkOnPrimaryContainer = Color(0xFFD9F7A8)
    val DarkSecondaryContainer = Color(0xFF0E3440)
    val DarkOnSecondaryContainer = Color(0xFFB6ECF7)
    val DarkTertiaryContainer = Color(0xFF2C2258)
    val DarkOnTertiaryContainer = Color(0xFFD6CCFF)
    val DarkErrorContainer = Color(0xFF4A1520)
    val DarkOnErrorContainer = Color(0xFFFFC2C7)

    val LightPrimaryContainer = Color(0xFFD6EFB0)
    val LightOnPrimaryContainer = Color(0xFF1B2E00)
    val LightSecondaryContainer = Color(0xFFBDE9F5)
    val LightOnSecondaryContainer = Color(0xFF00262F)
    val LightTertiaryContainer = Color(0xFFE3DBFF)
    val LightOnTertiaryContainer = Color(0xFF1F0A63)
    val LightErrorContainer = Color(0xFFFFDAD9)
    val LightOnErrorContainer = Color(0xFF410006)

    // --- True-black (OLED) ramp ------------------------------------------------------------
    val BlackContainerLowest = Color(0xFF000000)
    val BlackContainerLow = Color(0xFF06060A)
    val BlackContainerHigh = Color(0xFF14141A)
    val BlackContainerHighest = Color(0xFF1C1C24)
    val BlackSurfaceDim = Color(0xFF000000)
    val BlackSurfaceBright = Color(0xFF1C1C24)
}

@Immutable
data class PulseColors(
    val isDark: Boolean,
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val outline: Color,
    val work: Color,
    val rest: Color,
    val prepare: Color,
    val cooldown: Color,
    val destructive: Color,
    val onAccent: Color,
    val trueBlack: Boolean = false,
    /** Set when the user turned on the high-contrast switch. */
    val highContrast: Boolean = false,
    // Material tonal ramp. Defaults mirror the dark palette so a hand-built PulseColors
    // (previews, tests, the first frame) is still coherent.
    val surfaceContainerLowest: Color = PulsePalette.DarkContainerLowest,
    val surfaceContainerLow: Color = PulsePalette.DarkContainerLow,
    val surfaceContainer: Color = PulsePalette.Surface,
    val surfaceContainerHigh: Color = PulsePalette.DarkContainerHigh,
    val surfaceContainerHighest: Color = PulsePalette.DarkContainerHighest,
    val surfaceDim: Color = PulsePalette.DarkSurfaceDim,
    val surfaceBright: Color = PulsePalette.DarkSurfaceBright,
    val outlineVariant: Color = PulsePalette.DarkOutlineVariant,
    val primaryContainer: Color = PulsePalette.DarkPrimaryContainer,
    val onPrimaryContainer: Color = PulsePalette.DarkOnPrimaryContainer,
    val secondaryContainer: Color = PulsePalette.DarkSecondaryContainer,
    val onSecondaryContainer: Color = PulsePalette.DarkOnSecondaryContainer,
    val tertiaryContainer: Color = PulsePalette.DarkTertiaryContainer,
    val onTertiaryContainer: Color = PulsePalette.DarkOnTertiaryContainer,
    val errorContainer: Color = PulsePalette.DarkErrorContainer,
    val onErrorContainer: Color = PulsePalette.DarkOnErrorContainer,
    val inverseSurface: Color = PulsePalette.TextPrimary,
    val inverseOnSurface: Color = PulsePalette.Ink,
    val inversePrimary: Color = Color(0xFF4C7A0F),
) {
    /** Colour used for a phase's fill (or its label, when [asFill] is false). */
    fun phaseColor(kind: PhaseKind, asFill: Boolean = true): Color = when (kind) {
        PhaseKind.WORK, PhaseKind.WARM_UP -> work
        PhaseKind.REST -> rest
        PhaseKind.TRANSITION -> rest
        PhaseKind.PREPARE -> prepare
        PhaseKind.COOLDOWN -> cooldown
        PhaseKind.CUSTOM -> textSecondary
    }

    /** Neutral fill for labels that are *not* phases (workout type, counts, "starter"). */
    val neutralFill: Color get() = surfaceContainerHigh

    /** Text colour that sits on top of [neutralFill]. */
    val onNeutralFill: Color get() = textPrimary

    /** Subtle track behind progress rings and scrubbers — visible, never competing with the fill. */
    val track: Color get() = outline.copy(alpha = if (isDark) 0.28f else 0.24f)
}

val LocalPulseColors = staticCompositionLocalOf {
    pulseColors(dark = true, trueBlack = false, highContrast = false)
}

val LocalPulseDimens = staticCompositionLocalOf { PulseDimens() }

/** Single spacing scale (4 dp base) — every screen uses these steps only. */
@Immutable
data class PulseDimens(
    val xs: Dp = 4.dp,
    val s: Dp = 8.dp,
    val m: Dp = 12.dp,
    val l: Dp = 16.dp,
    val xl: Dp = 24.dp,
    val xxl: Dp = 32.dp,
    val huge: Dp = 48.dp,
    val minTouchTarget: Dp = 48.dp,
    val cardRadius: Dp = 20.dp,
    val chipRadius: Dp = 999.dp,
)

/** Motion settings, including the reduced-motion switch required by the accessibility spec. */
@Immutable
data class PulseMotion(val reduced: Boolean) {
    /** Duration in ms, collapsed to 0 when the user prefers reduced motion. */
    fun duration(normal: Int): Int = if (reduced) 0 else normal
}

val LocalPulseMotion = staticCompositionLocalOf { PulseMotion(reduced = false) }

/** Tabular figures keep the countdown from shifting width between digits. */
val TimerTextStyle = TextStyle(
    fontFeatureSettings = "tnum",
    fontFamily = FontFamily.Default,
)

fun pulseTypography(): Typography {
    val base = Typography()
    return base.copy(
        displayLarge = base.displayLarge.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.Bold),
        displayMedium = base.displayMedium.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.Bold),
        displaySmall = base.displaySmall.copy(fontFeatureSettings = "tnum", fontWeight = FontWeight.SemiBold),
        headlineMedium = base.headlineMedium.copy(fontWeight = FontWeight.SemiBold),
        headlineSmall = base.headlineSmall.copy(fontWeight = FontWeight.SemiBold),
        titleLarge = base.titleLarge.copy(fontWeight = FontWeight.SemiBold),
        labelLarge = base.labelLarge.copy(fontWeight = FontWeight.SemiBold, letterSpacing = 0.5.sp),
        labelSmall = base.labelSmall.copy(letterSpacing = 0.8.sp),
    )
}

@Composable
fun PulseTheme(
    themeMode: ThemeMode,
    dynamicColor: Boolean,
    highContrast: Boolean,
    reducedMotion: Boolean,
    content: @Composable () -> Unit,
) {
    val systemDark = isSystemInDarkTheme()
    val dark = when (themeMode) {
        ThemeMode.SYSTEM -> systemDark
        ThemeMode.LIGHT -> false
        ThemeMode.DARK, ThemeMode.TRUE_BLACK -> true
    }
    val trueBlack = themeMode == ThemeMode.TRUE_BLACK
    val colors = pulseColors(dark = dark, trueBlack = trueBlack, highContrast = highContrast)
    val context = LocalContext.current
    // Dynamic colour is a wallpaper-derived palette: it can only decorate the shell, and it is
    // never offered while high contrast is on because a wallpaper cannot promise our ratios.
    val wantsDynamic = dynamicColor && !highContrast && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S
    val colorScheme = when {
        !wantsDynamic -> colors.toMaterialScheme()
        dark -> dynamicDarkColorScheme(context)
        else -> dynamicLightColorScheme(context)
    }
    CompositionLocalProvider(
        LocalPulseColors provides colors,
        LocalPulseDimens provides PulseDimens(),
        LocalPulseMotion provides PulseMotion(reducedMotion),
    ) {
        MaterialTheme(colorScheme = colorScheme, typography = pulseTypography(), content = content)
    }
}

enum class ThemeMode { SYSTEM, LIGHT, DARK, TRUE_BLACK }

fun pulseColors(dark: Boolean, trueBlack: Boolean, highContrast: Boolean): PulseColors {
    return if (dark) {
        PulseColors(
            isDark = true,
            background = if (trueBlack) PulsePalette.TrueBlack else PulsePalette.Ink,
            surface = if (trueBlack) PulsePalette.TrueBlackSurface else PulsePalette.Surface,
            surfaceRaised = if (trueBlack) PulsePalette.BlackContainerHigh else PulsePalette.SurfaceRaised,
            textPrimary = if (highContrast) PulsePalette.HighContrastText else PulsePalette.TextPrimary,
            textSecondary = if (highContrast) PulsePalette.HighContrastSecondary else PulsePalette.TextSecondary,
            outline = if (highContrast) Color(0xFF6B7899) else PulsePalette.Outline,
            work = if (highContrast) Color(0xFFC7F87C) else PulsePalette.Work,
            rest = if (highContrast) Color(0xFF8BE6F7) else PulsePalette.Rest,
            prepare = if (highContrast) Color(0xFFFFD79A) else PulsePalette.Prepare,
            cooldown = if (highContrast) Color(0xFFCBBDFF) else PulsePalette.Cooldown,
            destructive = PulsePalette.Destructive,
            onAccent = PulsePalette.OnAccent,
            trueBlack = trueBlack,
            highContrast = highContrast,
            surfaceContainerLowest = if (trueBlack) PulsePalette.BlackContainerLowest else PulsePalette.DarkContainerLowest,
            surfaceContainerLow = if (trueBlack) PulsePalette.BlackContainerLow else PulsePalette.DarkContainerLow,
            surfaceContainer = if (trueBlack) PulsePalette.TrueBlackSurface else PulsePalette.Surface,
            surfaceContainerHigh = if (trueBlack) PulsePalette.BlackContainerHigh else PulsePalette.DarkContainerHigh,
            surfaceContainerHighest = if (trueBlack) PulsePalette.BlackContainerHighest else PulsePalette.DarkContainerHighest,
            surfaceDim = if (trueBlack) PulsePalette.BlackSurfaceDim else PulsePalette.DarkSurfaceDim,
            surfaceBright = if (trueBlack) PulsePalette.BlackSurfaceBright else PulsePalette.DarkSurfaceBright,
            outlineVariant = PulsePalette.DarkOutlineVariant,
            primaryContainer = PulsePalette.DarkPrimaryContainer,
            onPrimaryContainer = PulsePalette.DarkOnPrimaryContainer,
            secondaryContainer = PulsePalette.DarkSecondaryContainer,
            onSecondaryContainer = PulsePalette.DarkOnSecondaryContainer,
            tertiaryContainer = PulsePalette.DarkTertiaryContainer,
            onTertiaryContainer = PulsePalette.DarkOnTertiaryContainer,
            errorContainer = PulsePalette.DarkErrorContainer,
            onErrorContainer = PulsePalette.DarkOnErrorContainer,
            inverseSurface = Color(0xFFE4E8F2),
            inverseOnSurface = PulsePalette.Ink,
            inversePrimary = Color(0xFF4C7A0F),
        )
    } else {
        PulseColors(
            isDark = false,
            background = PulsePalette.LightBackground,
            surface = PulsePalette.LightSurface,
            surfaceRaised = PulsePalette.LightSurfaceRaised,
            textPrimary = if (highContrast) Color(0xFF000000) else PulsePalette.LightTextPrimary,
            textSecondary = if (highContrast) Color(0xFF2A3247) else PulsePalette.LightTextSecondary,
            outline = PulsePalette.LightOutline,
            work = PulsePalette.WorkLight,
            rest = PulsePalette.RestLight,
            prepare = PulsePalette.PrepareLight,
            cooldown = PulsePalette.CooldownLight,
            destructive = PulsePalette.DestructiveLight,
            onAccent = Color.White,
            highContrast = highContrast,
            surfaceContainerLowest = PulsePalette.LightContainerLowest,
            surfaceContainerLow = PulsePalette.LightContainerLow,
            surfaceContainer = PulsePalette.LightBackground,
            surfaceContainerHigh = PulsePalette.LightContainerHigh,
            surfaceContainerHighest = PulsePalette.LightContainerHighest,
            surfaceDim = PulsePalette.LightSurfaceDim,
            surfaceBright = PulsePalette.LightSurfaceBright,
            outlineVariant = PulsePalette.LightOutlineVariant,
            primaryContainer = PulsePalette.LightPrimaryContainer,
            onPrimaryContainer = PulsePalette.LightOnPrimaryContainer,
            secondaryContainer = PulsePalette.LightSecondaryContainer,
            onSecondaryContainer = PulsePalette.LightOnSecondaryContainer,
            tertiaryContainer = PulsePalette.LightTertiaryContainer,
            onTertiaryContainer = PulsePalette.LightOnTertiaryContainer,
            errorContainer = PulsePalette.LightErrorContainer,
            onErrorContainer = PulsePalette.LightOnErrorContainer,
            inverseSurface = Color(0xFF2A3145),
            inverseOnSurface = Color(0xFFF2F5FB),
            inversePrimary = PulsePalette.Work,
        )
    }
}

/**
 * Material colour scheme for the app shell.
 *
 * Every Material3 role is bound to a PULSE token: the tonal ramp drives dialogs, menus, the bottom
 * bar, chips and switches, so no component falls back to the framework's default purple-grey.
 * Interval phase colours stay semantic — see [PulseColors.phaseColor]. Dynamic colour is resolved
 * in [PulseTheme], never here, because it needs a composition and must not touch phase colours.
 */
fun PulseColors.toMaterialScheme(): ColorScheme {
    val base = if (isDark) {
        darkColorScheme(
            primary = work,
            onPrimary = onAccent,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            secondary = rest,
            onSecondary = onAccent,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = cooldown,
            onTertiary = onAccent,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            error = destructive,
            onError = onAccent,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            background = background,
            onBackground = textPrimary,
            surface = surface,
            onSurface = textPrimary,
            surfaceVariant = surfaceContainerHigh,
            onSurfaceVariant = textSecondary,
            surfaceContainerLowest = surfaceContainerLowest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceDim = surfaceDim,
            surfaceBright = surfaceBright,
            outline = outline,
            outlineVariant = outlineVariant,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            inversePrimary = inversePrimary,
            scrim = Color.Black,
        )
    } else {
        lightColorScheme(
            primary = work,
            onPrimary = onAccent,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            secondary = rest,
            onSecondary = onAccent,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = cooldown,
            onTertiary = onAccent,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            error = destructive,
            onError = onAccent,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            background = background,
            onBackground = textPrimary,
            surface = surface,
            onSurface = textPrimary,
            surfaceVariant = surfaceContainerHigh,
            onSurfaceVariant = textSecondary,
            surfaceContainerLowest = surfaceContainerLowest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceDim = surfaceDim,
            surfaceBright = surfaceBright,
            outline = outline,
            outlineVariant = outlineVariant,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            inversePrimary = inversePrimary,
            scrim = Color.Black,
        )
    }
    return base
}

// --- WCAG helpers (also used by the contrast report generator) --------------------------------

fun relativeLuminance(color: Color): Double {
    fun channel(v: Float): Double {
        val c = v.toDouble()
        return if (c <= 0.03928) c / 12.92 else ((c + 0.055) / 1.055).pow(2.4)
    }
    return 0.2126 * channel(color.red) + 0.7152 * channel(color.green) + 0.0722 * channel(color.blue)
}

fun contrastRatio(a: Color, b: Color): Double {
    val la = relativeLuminance(a)
    val lb = relativeLuminance(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)
}

/**
 * Text colour that stays readable on an arbitrary tint: white on dark fills, ink on light ones.
 * Used wherever a caller supplies its own background tint.
 */
fun legibleOn(background: Color): Color =
    if (relativeLuminance(background) > 0.35) Color(0xFF0B1020) else Color(0xFFF5F7FB)
